addUser:	addUser.py
	./addUser.py jw666 Michael.Oranski@gmail.com !@#Jgh5643sd John Wick 1950-05-06 70 male

test:	addUser.py
	./addUser.py mo777 Michael.Oranski@gamil.com rtegwg89093qjtJG	Michael Oranski	1988-07-28 31 male

